name: Turbopack Nightly Release



jobs:
  turbopack_nightly:
    name: cut nightly Turbopack 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Tag nightly
        id: tag_version
        uses: ./.github/actions/turbopack-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "turbopack-"
