name: Turbopack Nightly Release

on:
  workflow_dispatch:

jobs:
  turbopack_nightly:
    name: build "save" nightly Turbopack 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Tag nightly
        id: tag_version
        uses: ./.github/actions/turbopack-bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "turbopack-"
